# TODO: Rename? Maybe spdk-wrapper-workflow?
name: SPDK per-patch tests

on:
  repository_dispatch:
    types:
      - per-patch-event

jobs:
  # TODO: Checkout common tests workflow in case it's changed in incoming commit and
  # use it here to enable-self testing.
  common-tests:
    uses: karlatec/spdk/.github/workflows/spdk-common-tests.yml@master
    with:
      # "Client payload" is all of the information Gerrit webhooks sends out.
      client_payload: ${{ toJson(github.event.client_payload) }}
    secrets: inherit
  # Add more jobs below if needed.
