name: Handle gerrit webhook

on:
  repository_dispatch:
    types:
      - gerrit-webhook

jobs:
  # "print-stuff" is only an example job entry, which is reusing "gerrint-change-printer" workflow.
  # Ultimately it should be replaced by other workflows and actions running SPDK tests
  print-stuff:
    uses: karlatec/spdk/.github/workflows/gerrit-change-printer.yml@master
    with:
      # "Client payload" is all of the information Gerrit webhooks sends out.
      client_payload: ${{ toJson(github.event.client_payload) }}
    secrets: inherit
