name: SPDK per-patch common tests

on:
  workflow_call:
    inputs:
      client_payload:
        required: false
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checking out from Github to reduce data transferred and time.
      # TODO: Seems this together with the next step (fetch change) can be replaced by a single step. Make it an action in future.
      - name: Checkout SPDK
        uses: actions/checkout@v4
        with:
          repository: spdk/spdk
          submodules: recursive

      - name: Fetch change from Gerrit
        run: |
          git fetch https://review.spdk.io/gerrit/spdk/spdk "${{ fromJson(inputs.client_payload).patchSet.ref }}" && git checkout FETCH_HEAD
          # Fetching submodules again, as the previous step might have changed the commit.
          git submodule update --init --recursive

      # TODO: Create a pre-built image with all dependencies and use it here instead of installing every time.
      - name: Install buils dependencies
        run: |
          sudo ./scripts/pkgdep.sh --uring --developer-tools
          # No idea why meson is not installed by the script above, need to figure out later.
          sudo apt-get install meson python3-pyelftools

      # autotest_common.sh sets all there flags to 0 by default, but we explicitly list them here to
      # know what's missing from the build.
      - name: Prepare autotest configuration file
        run: |
          cat <<- EOF >> autotest.conf
            SPDK_RUN_VALGRIND=0
            SPDK_TEST_UNITTEST=1
            SPDK_TEST_BLOCKDEV=1
            SPDK_TEST_ISAL=1
            SPDK_TEST_REDUCE=1
            SPDK_TEST_VBDEV_COMPRESS=1
            SPDK_TEST_CRYPTO=1
            SPDK_TEST_FTL=1
            SPDK_TEST_OCF=0
            SPDK_TEST_RAID=1
            SPDK_TEST_RBD=1
            SPDK_TEST_URING=1
            SPDK_TEST_NVME_CUSE=1
            SPDK_TEST_BLOBFS=1
            SPDK_TEST_VFIOUSER=1
            SPDK_TEST_DAOS=0
            SPDK_RUN_ASAN=1
            SPDK_RUN_UBSAN=1
            SPDK_TEST_XNVME=1
          EOF

      # TODO: Build should be done in a separate job or step, so we can cache the build artifacts and use in jobs
      # running other tests.
      - name: Build SPDK and run unit tests
        run: |
          rootdir=$GITHUB_WORKSPACE

          source ./test/common/autobuild_common.sh ./autotest.conf
          unittest_build
          ./test/unit/unittest.sh

  # TODO: Commented out for now. Will re-enable after all fixes are done and workflows are approved after review.
  # TODO: This is going to be reusable - make it a separate action.
  # report:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - print-patchset
  #   steps:
  #     - name: Report results
  #       run: |
  #         # Credits to https://github.com/spdk-community-ci/dispatcher/blob/main/.github/workflows/autorun.yml
  #         set -e

  #         VOTE=-1
  #         if [[ "${{ needs.print-patchset.result }}" == "success" ]]; then
  #           VOTE=1
  #         fi

  #         # For demonstration purposes, as not to set any actual vote and only comment.
  #         VOTE=0

  #         # curl -X POST https://review.spdk.io/gerrit/a/changes/${{ fromJson(inputs.client_payload).change.number }}/revisions/${{ fromJson(inputs.client_payload).patchSet.number }}/review \
  #         # --user "${{ secrets.GERRIT_BOT_USER }}:${{ secrets.GERRIT_BOT_HTTP_PASSWD }}" \
  #         # --header "Content-Type: application/json" \
  #         # --data "{'message': '$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID', 'labels': {'Verified': $VOTE}}" \
  #         # --fail-with-body
